//! Main Strings

const appName = "ChatZon AI",
    credits = "@pavin__das",
    appversion = "Version 1.0",

//! Home Strings
    welcome = "Welcome",
    welcomToApp = "Welcome to ChatZon AI",
    name = "Name",
    nameHint = "Your Name",
    email = "Email",
    phone = "Phone",
    phoneHint = "+91 9876543210",
    emailHint = "admin@admin.com",
    enterEmail = "Enter your email address",
    password = "Password",
    passwordHint = "******",
    enterPass = "Enter your password",
    retypePass = "Confirm Password",
    forgetPass = "Forget Password",
    enterusernames = "Enter your username",
    enterPhone = "Enter your phone number",
    enterBio = "Enter your bio",
    login = "Log In",
    signup = "Sign Up",
    createNewAccount = "or, Create a new account?",
    dontHaveAcc = "Don't have an account?",
    loginWith = "Log In with",
    logout = "Log Out",
    googleSign = "SignUp with Google",
    selectCountry = "Select Country",
    privacyPolicy = "Privacy Policy",
    termsCond = "Terms and Condition",
    privacyAndPolicy =
        """Read our Privacy Policy. Tap "Agree and continue" to \naccept the Terms of Service.""",
    agreeAndContinue = "Agree and continue",
    alreadyHaveAcc = "Already have an account? ",
    buyYourFav = "Buy Your Favorites",
    welcomeBack = "Welcome Back",
    createNewAcc = "Create An Account",
    verifyPhone = "Verify your phone number",
    verifyEmail = "Verify your email address",
    verifyPass = "Verify your password",
    resendCode = "Resend Code",
    verifyCode = "Verify Code",
    resend = "Resend",
    loading = "Loading...",
    emptyMail = "Email is empty",
    emptyPass = "Password is empty",
    emptyName = "Name is empty",
    emptyPhone = "Phone number is empty",
    enterDetails = "Enter details",
    cancel = "Cancel",
    home = "Home",
    edit = "Edit",
    explore = "Explore",
    search = "Search",
    postTo = "Post to",
    createPost = "Create a post",
    takePhoto = "Take a photo",
    choosePhoto = "Choose a photo",
    download = "Download",
    downloadNow = "Download Now",
    like = "Like",
    comment = "Comment",
    share = "Share",
    save = "Save",
    next = "Next",
    finish = "Finish",

    //! Account Strings
    myAccount = "My Account",
    editProfile = "Edit Profile",
    favorites = "Favorites",
    yourFavoriteIsEmpty = "Your Favorites is Empty",
    account = "Account",
    pageDoesntExist = "Page doesn't exist",
    somethingWentWrong = "Something went wrong",
    tryAgainLater = "Try Again later",

    //! Chat Strings
    aiChatBot = "AI Chat Bot",
    aiImageGen = "AI Image Generator",
    langtranslator = "Language Translator",
    asMekAnything = "Ask me Anything",
    askMeAnythingYouWant = "Ask me anything you want . . .",
    imgToReality = "Imagination to Reality",
    imgAnything =
        "Just imagine anything & let me know, I will create something wonderful for you",
    askMeFrnd =
        "I can be your best friend & You can ask me anything \nI will help you!";
